### PR TITLE
Omit email addresses from author information

### PR DESCRIPTION
**Pull request by lassik**

### CODE REVIEW

**Comment by arthurgleckler** [comment]
Only update the SRFI document.  Leave the index.html and REaDME.org files alone since they're generated.  Once we update srfi-data.scm, I'll regenerate everything and those files will be updated, too.  In the meantime, I don't want them to be inconsistent because I might regenerate them and restore their contents.

**Comment by lassik** [comment]
OK. Force-pushed another attempt. Ready to merge.

**Comment by lassik** [comment]
@arthurgleckler OK?

**Comment by arthurgleckler** [comment]
Already done.

**Comment by lassik** [comment]
Nope. The email addresses are still in the document: https://srfi.schemers.org/srfi-31/srfi-31.html

**Comment by arthurgleckler** [comment]
On Fri, Mar 6, 2020 at 7:40 AM Lassi Kortela <notifications@github.com>
wrote:

> Nope. The email addresses are still in the document:
> https://srfi.schemers.org/srfi-31/srfi-31.html
>
> Weird. I thought you were talking about SRFI 52.  Gmail combined two email
threads into one, and I only saw the subject line at the top:

[scheme-requests-for-implementation/srfi-52] Omit email addresses from
author information (#1)


But that wasn't the subject line of the message to which I was replying.
That one was hidden.

In any case, I've merged and pushed the change.

Thanks, and sorry for the confusion.

**Pull request merged**
